# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.Page'),
        ),
    ]
