# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20160319_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='page',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
