# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20160319_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='contents',
        ),
    ]
