# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20160319_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
