# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20160320_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='sourcefile',
            field=models.FileField(upload_to='profile_file'),
        ),
    ]
