# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_auto_20160320_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, max_length=128)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contents', models.CharField(default=None, max_length=600)),
                ('dislikes', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Page')),
            ],
        ),
    ]
