# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contents', models.CharField(default=None, max_length=600)),
            ],
        ),
    ]
