# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-09 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('amount', models.IntegerField(default=0)),
                ('creditcode', models.IntegerField(default=0)),
                ('lisitngid', models.IntegerField(default=0)),
                ('months', models.IntegerField(default=0)),
                ('payway', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
    ]
