# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-09 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_auto_20170409_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
